### ISSUE TITLE
could you please post some basic user instructions 

### ISSUE THREAD

**Issue by Ritchoau** [muhd-umer/deep-suppressor#16]
extremally new to this kinda thing and tried to get his to work on my windows pc using anaconda. 

ran into constant errors with the code and despite my best effort i could not get it to work. 

would you be willing to post a basic setup guide and a bit more simplistic explanation of its operation for us lemans? :)

**Comment by muhd-umer** [comment]
Sure, I'd be happy to help you with that. I'll be finalizing the documentation on **Thursday, 06/06/2023**, and I'll make sure to include a basic setup guide and a more simplistic explanation of the operation of the project.

I'm sorry to hear that you're having trouble getting it to work on Windows. I developed and tested the project entirely on Windows Subsystem for Linux (WSL), so it's possible that some things aren't functioning correctly on Windows. You could follow the [official guide](https://learn.microsoft.com/en-us/windows/wsl/install) by Microsoft on how to setup WSL until I finalize the guide.

Moreover, I'll also be making the [included notebook](https://github.com/muhd-umer/deep-suppressor/blob/main/notebooks/demo.ipynb) compatible with Google Colaboratory, so you can run it on the cloud without any local installation.

Muhammad Umer
